language: go
go:
- 1.13.x
env:
  global:
  - GO111MODULE: 'on'
  - NEBULA_EMAIL: nebula-team@puppet.com
  - secure: o67qTsynCkX85r3w/B9s1SkOBSEInNEIPx/wGh0+tHVllPRmj+ciEpH9HvWS5vjny6N3g6qdejEyRt4QSIdt2X7gHmDlOLrNTp7UDf+Tu8hI4EtQehL44VP7UCcwuympjrCmAkHlOKvHGhhnuQGcfJYXJM8ijHVBFa3+ZD8sfWJ4XFiS8aG4S3TIQ+E1CDvReKzROTV7yaQqRt0L2SHJpEiy/XAsUGp0/xcp/CC5g5yMy7LEb7Wwbpl0EiO585tzquHPFwIs4dM9YfNUIj6eH4eMFJ1tw29Yu9MR2rPDX3NShuoqOt7GkswmRcq5j8zNHWMhZvu92Y9QL1lluRIYWNepWXDvlKv+8ZrTDoSP8VdQcfRwGVGp+Jw/tI5nxJTxdObvnLAXX436ZVgSW65Mai2t7BYVpMU7a3B/yF+lsvKleDcuIphlgzwt7kYju2ZldC7AdjdH2uhGaICAlWp5ESM8J2Jff2dNYDfvL9qJtI8ua27zBMf6eAFYUTouDsN2dxtNC2cJZmvnd3qw2yub46oDRL5JVlyWJt1POwl51p36NGRV7Gmx0voumCEFwywMoF5+xQ5NqHclbTsDENX/n+FFQly9XgHWhRmF5pC4whlfz1ezZLKlq89mMQrsNsPsJSKeLA0Y3bA4W72PT4QH2I3wtPjNgA9Fw4UcuSbEV6M=
  - secure: KSeV/KzTSYJFUkk/y1t6nd7VxZC6/g5ok91k0lbk/NA4/c5YfLIusCP/iKw8YvGaMbHvUekXR9OqdjbPq1yA7x9BdwGjR9zLbAO+f4HXkR5RWVXrEY04OjAWBmazJtEnNfyshVCP/7nhZ0lXBC0y+LfbN9lu/gdkv/mwUoDD4wfSULyDJEPgbDwPbNuL4t9qBZgjzik8B1cQJqMaJbo/IW8LaQtaONR2K9Q02rJo/K1dav1f04c8v6Hu38mda2GrlbXaccyR4M0qIeTdSoWcA627hZHWqlKav85A0rCwnB/6e/XZ8N61gYeOFUVLrYuQhrC6Cy0VPqLmk69eZEhLzB3NWwmZSuVI7PPAwoprFGLu3T6X+QebTmEjsRJrxuOYru5s8U5k5ta7lr09ZHOmKgSMOYPmdURKuWiQKBpUItuWfR1rZRhddJ3Q0XQjoAgcJya3368tpG/t3Hzr0L7gHtm519vx6pGhH4UozypFV3eL1qOLz1hC3nvbxuyZ+E+aX9qP2E85uiveaNYtaQ8HL8tO8BXPlwbtx/oHy/IuNNioanT9u8XUn24ev3Z7P4SEv25oehmVisU3a9b6el4FPg/0vDwg2aRl0jm4+lziiMq38tTXwupHkj6aVbAbmV2m3rpKWmH6tsX3tdDU9vI01kGrd9WL54PwM5FVumeb9M4=
jobs:
  include:
  - stage: test
    script:
    - "./scripts/ci test"
  - stage: build
    before_script:
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk;
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com |
      bash; fi
    - source "$HOME"/google-cloud-sdk/path.bash.inc
    - openssl aes-256-cbc -K $encrypted_35392154f715_key -iv $encrypted_35392154f715_iv
      -in scripts/nebula-gcloud-service-account.json.enc -out scripts/nebula-gcloud-service-account.json
      -d
    - gcloud auth activate-service-account --key-file scripts/nebula-gcloud-service-account.json
    - gcloud --quiet auth configure-docker
    script:
    - "./scripts/ci build"
    - "./scripts/ci release"
  - stage: deploy
    script:
    - "./scripts/ci deploy"
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    template:
    - "<%{compare_url}|%{commit_subject}> | %{author}"
    - "%{repository_slug} %{branch} | <%{build_url}|#%{build_number}> %{result} in
      %{elapsed_time}"
    rooms:
      secure: sTvyXPL00HHFJM6zDFG9XimZQRcE2hauE7iASHr+E3fWq4O1NqyDIv7X+btSGD/Q3Ju09CMrMulrrKZ2dNBD4XrMNaTztQAu+CP7Kbbwxa6cGKhTQJxDrq0wQ+QlER/FTm6TcTOFpl6zQqtDkorEZuNH1p9SAi66MwxZJHN5bX/IU/6wNfrl7zOLMmNEP1vNKpxHl0ULVTMD8min/+aDu+aVmC1+sbioJ22YTvRcUiM1tBtfPT1gL0c4k084xvK7tjLzoc73USWvZZfw6EUnC7bAD5CdJ5WbXs4WQA0Z8+sBWrUZk3eiebjRYTfEc1O7ky7dtVdsovJLdDUlFkQxvgUTW3ypOwfL59+xLKgQjDQtebIAO2T6tdvmkxlM8BxfK3RVbGJodvius9+S0TuHGzMeW5aCR58mKK12JkH3D1XNpQ6zUnca1/gG89QZh6PNwCppceIu0wnyf6oR/TfTXrRkx/qJ0ZbgX1AKMgTiIOV4QO6j7uFDon3pqvBMBZz3GBf/TKpp1mkc7/NO7HE6JskXttHFaHeAlm3CDtcoPbc70bVfPbTp7JGHMlIJ1ByvLgJ9o3SR1V5TkjMF0rk/AjhXAmkAPg3V3hIIUdf1MnOzA5bwqDtfK0FDxSGffFDJgg5FuMhZQyzxEQrtUPiGU5CykYD/H1UAAX8xwm9NsQo=
