language: go
go:
- 1.13.x
env:
  global:
  - GO111MODULE: 'on'
  - NEBULA_EMAIL: nebula-team@puppet.com
  - secure: Vap5EoRud7spvF1eAF7DjeLTSSHuXa9KI1reTgHtUs/cIaorePipyu5ZKzBgRiEC9l5iXoawKmH0b+6sPtjNP09ImcKiN9rk4mRrQy24FPz4Q0AfTw0PO925D0phsfA6itT/2SKTKfQL8ojY94k+tRrHiuO3RCx80fsQfj9ejsNGC54VKqAmIUAQr5AyapdHuO0fWdQBYA0Sz/xipSLuPEdCkM9KKjoiyJpt5ExBXPDtflq45UZFFUXN/rH8K76OAGhvyTXuxCRNgd7RF6EvjczzzWDeg1SIAG9nH3Ug7Q7XQXgjyFfOqWjD2HgfTfBJg5qpohC140u2Hy0k52we4Bd8GbOTFfqnQgTqqlqgN5/H88jRVDcK03CRMpO39uyIFmuSJv0t7NVfPM5U4cXehGbq60cOctbOoV3mN3KqvP2pGamFORrCW4eIbK6gwIw93YUQrdGWhaOHw4DFk3k2J40bfkBa012EYA/M0IDGpSHP97fsuGq8mD7GafmtrdkbVRobbn3wlqr4+izV52sTS1lmJvUwKw+iXqnheN7xCmAm6odpeHWjBENzVuzE0BAKs3NUhvtJIvvSaVC5+HHT8mTjiMzib6fHddycmZ9AuWIXpSOux9ttY07WxvXojLPSO31J/CWCMb2Y2pT09H4YwQZLqzIURWEXvuEObrtdCts=
  - secure: IXSGRmvOlxunE27/IOW348zbJFT1vCRewGeJV6Xi4GYud8kLdIXf3IQxb5jV1E8J+cNAoCntgRSMWnIKbW3stc1LAVBojM+aLO4TAVlX0jpZhVyV5StlsZdCuM7v8dOOslUHivW8jUkzJum9+lWQMrmdrqarjhqcg4QtozgSqMV1V4ZRUGm7rLe2X6h7OzaQwd6o3+VAtrY8sN6KjoEQdrTNUllS3L3Yhicgba7fXXEY8DvAeHQJ9s0E52vJv8kC7k6N6bnK5FnjbS39YwjBVQZZOQsBOSKmLh16NNkV6TxggRpF1oix6nfVjQhuHPL3sgrPwUoAieMgty9pfoksl9vfkFmvbt+5nhWIjDMz/N3Wn0ErlJ69aKcq83kgipuxmjcu6VVYFC7+e+6Z0rGQtC8viFuPWxAbwjbnW441cWVP1hRImAj3qEHYJlFt3rYp3pQWmo9U1NgysHd7OtIA6TN8tOTgObEz6eL8EBZFMOSDTiUjkMZZu19OuG+9sjMAMqsUF/5AT74jZSmfAS+D55FjnChP9hrQosBhGgXIGxpyLtky9yCCJDr6gm6DROnLJGw4qoXYzO2gZh8hH4zDkuRrqEMdmBRe4aRCHNo5jd275JoILkmkY/B0urheAHnl/4KLq5rWDM1ZEYrZWrm+BvyVW9yfkuk0Zn4Nbgftioc=
jobs:
  include:
  - stage: test
    before_script:
    - curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64"
    - chmod +x ./kind
    - export KUBECONFIG=/tmp/kubeconfig-kind
    - ./kind create cluster
    script:
    - RELAY_TEST_E2E_KUBECONFIG="${KUBECONFIG}" ./scripts/ci test
  - stage: build
    before_script:
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk;
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com |
      bash; fi
    - source "$HOME"/google-cloud-sdk/path.bash.inc
    - openssl aes-256-cbc -K $encrypted_35392154f715_key -iv $encrypted_35392154f715_iv
      -in scripts/nebula-gcloud-service-account.json.enc -out scripts/nebula-gcloud-service-account.json
      -d
    - gcloud auth activate-service-account --key-file scripts/nebula-gcloud-service-account.json
    - gcloud --quiet auth configure-docker
    script:
    - "./scripts/ci build"
    - "./scripts/ci release"
  - stage: deploy
    script:
    - "./scripts/ci deploy"
