apiVersion: v1
kind: Namespace
metadata:
  name: workflow-run-1234
---
apiVersion: nebula.puppet.com/v1
kind: SecretAuth
metadata:
  name: workflow-run-1234
  namespace: workflow-run-1234
spec:
  workflowID: workflow-4321
  workflowRunID: workflow-run-1234
